promise.then(f1).catch(f2);

promise.then(f1, f2);

// Ошибка будет обработана только в первой строке